apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-push
spec:
  description: |
    This pipeline clones a git repo, builds a Docker image with buildah and
    pushes it to a registry
  params:
    - name: repo-url
      type: string
    - name: image-reference
      type: string
    - name: dockerfile
      type: string
    - name: context
      type: string
  workspaces:
    - name: shared-data
    - name: docker-credentials
    - name: git-credentials
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: main
      workspaces:
        - name: output
          workspace: shared-data
        - name: ssh-directory
          workspace: git-credentials
    - name: build-push
      runAfter: ["fetch-source"]
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: $(params.image-reference)
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: CONTEXT
          value: $(params.context)
        - name: SKIP_PUSH
          value: false
        - name: FORMAT
          value: docker
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: docker-credentials
    - name: helm-upgrade-from-source
      runAfter: ["build-push"]
      taskRef:
        name: helm-upgrade-from-source
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: charts_dir
          value: Helm/frontend
        - name: release_version
          value: v1.0.0
        - name: release_name
          value: helm-source-sample
        - name: overwrite_values
          value: "autoscaling.enabled=true,autoscaling.maxReplicas=3"
        - name: upgrade_extra_params
          value: "--force"