apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: backend-clone-build-push-run
spec:
  serviceAccountName: pipeline-sa
  pipelineRef:
    name: clone-build-push
  podTemplate:
    securityContext:
      fsGroup: 65532
  params:
    - name: repo-url
      value: git@github.com:djmelman/ONPK.git
    - name: image-reference
      value: tomastaptik/backend_tekton:1.0
    - name: dockerfile
      value: DockerFiles/backend/Dockerfile
    - name: context
      value: DockerFiles/backend
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: git-credentials
      secret:
        secretName: git-credentials
    - name: docker-credentials
      secret:
        secretName: docker-credentials
