apiVersion: v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app: {{ .Values.frontend.name }}  
spec:
  containers:
    - name: {{ .Values.frontend.name }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
