apiVersion: v2
name: backend
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.0.0"

dependencies:
  - name: mongodb
    version: 12.0.0
    repository: https://charts.bitnami.com/bitnami